### ISSUE TITLE
playbook installation instructions broken as written

### ISSUE THREAD

**Issue by atothRedHat** [keylime/keylime-docs#39]
While trying to deploy keylime from my laptop onto a remote node, using the installation instructions as written, the following error appear: 
"user@localhost ansible-keylime-master]$ ansible-playbook -i 10.1.4.3 ./playbook.yml
 [WARNING]: Unable to parse /home/user/Keylime/ansible-keylime-master/10.1.4.3
as an inventory source

 [WARNING]: No inventory was parsed, only implicit localhost is available

 [WARNING]: provided hosts list is empty, only localhost is available. Note
that the implicit localhost does not match 'all'

ERROR! the role 'fubarhouse.rust' was not found in /home/user/Keylime/ansible-keylime-master/roles:/home/user/.ansible/roles:/usr/share/ansible/roles:/etc/ansible/roles:/home/user/Keylime/ansible-keylime-master

The error appears to be in '/home/user/Keylime/ansible-keylime-master/playbook.yml': line 10, column 7, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

  roles:
    - fubarhouse.rust
      ^ here
"

expecting the playbook to just run error free base on the instructions content.

**Comment by atothRedHat** [comment]
This may just be a coding bug in the play book but opening this issue to track it if there is more info needed in the instructions as well.

**Comment by atothRedHat** [comment]
instructions need to add the sourcing\installation of the fubarhouse.rust ansible galaxy role before running the playbook

**Comment by lukehinds** [comment]
close this one now, as we removed the fubarhouse role
