### ISSUE TITLE
There are two Cloud Verifier sections in the REST APIs doc

### ISSUE THREAD

**Issue by MikeSpreitzer** [keylime/keylime-docs#59]
I see https://keylime-docs.readthedocs.io/en/latest/rest_apis.html#cloud-verifier-cv and https://keylime-docs.readthedocs.io/en/latest/rest_apis.html#id1, both saying they are about "Cloud verifier (CV)".  Their content looks similar but not identical.  I do not understand what is going on here.

**Comment by lukehinds** [comment]
Hi @MikeSpreitzer , I see the confusion. I will take this as an issue to fix this as there is some duplication and clean this up. I will tag you on the PR.

**Comment by THS-on** [comment]
This is now fixed with #63.
